name: Test rsync on FreeBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test rsync on FreeBSD
    steps:
    - uses: actions/checkout@v4
      fetch-depth: 0
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y bash autotools m4 devel/xxhash zstd liblz4 python3 archivers/liblz4
        run: |
          freebsd-version
          ./configure --with-rrsync --disable-md2man
          make
          ./rsync --version
          ./rsync-ssl --no-motd download.samba.org::rsyncftp/ || true
    - name: save artifact
      uses: actions/upload-artifact@v3
      with:
        name: freebsd-bin
        path: |
          rsync
          rsync-ssl
          rrsync
